services:
  db:
    image: mysql:8.0
    container_name: library_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: minhchitran2006  # Mật khẩu root (tự đặt)
      MYSQL_DATABASE: LibraryDB      # Tên DB muốn tạo
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql # Tự động chạy file schema.sql khi khởi tạo lần đầu
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: library_app
    depends_on:
      - db  # Chờ DB chạy xong mới chạy App
    volumes:
      - .:/app  # Mount code hiện tại vào container (để sửa code là cập nhật luôn)
    stdin_open: true # Để nhập liệu được (input)
    tty: true        # Để hiện giao diện console
    environment:
      - DB_HOST=db # Tên service db ở trên

volumes:
  mysql_data: